from election import Election


def setup():
    # https://www.electionresults.govt.nz/electionresults_2020_preliminary/
    the_election = Election(2020)

    the_election.add_party('ACT New Zealand')
    the_election.add_party('Advance NZ')
    the_election.add_party('Aotearoa Legalise Cannabis Party')
    the_election.add_party('Green Party')
    the_election.add_party('HeartlandNZ')
    the_election.add_party('Labour Party')
    the_election.add_party('Māori Party')
    the_election.add_party('National Party')
    the_election.add_party('New Conservative')
    the_election.add_party('New Zealand First Party')
    the_election.add_party('NZ Outdoors Party')
    the_election.add_party('ONE Party')
    the_election.add_party('Social Credit')
    the_election.add_party('Sustainable New Zealand Party')
    the_election.add_party('TEA Party')
    the_election.add_party('The Opportunities Party (TOP)')
    the_election.add_party('Vision New Zealand')

    the_election.add_electorate('Auckland Central')
    the_election.add_electorate('Banks Peninsula')
    the_election.add_electorate('Bay of Plenty')
    the_election.add_electorate('Botany')
    the_election.add_electorate('Christchurch Central')
    the_election.add_electorate('Christchurch East')
    the_election.add_electorate('Coromandel')
    the_election.add_electorate('Dunedin')
    the_election.add_electorate('East Coast')
    the_election.add_electorate('East Coast Bays')
    the_election.add_electorate('Epsom')
    the_election.add_electorate('Hamilton East')
    the_election.add_electorate('Hamilton West')
    the_election.add_electorate('Hutt South')
    the_election.add_electorate('Ilam')
    the_election.add_electorate('Invercargill')
    the_election.add_electorate('Kaikōura')
    the_election.add_electorate('Kaipara ki Mahurangi')
    the_election.add_electorate('Kelston')
    the_election.add_electorate('Mana')
    the_election.add_electorate('Māngere')
    the_election.add_electorate('Manurewa')
    the_election.add_electorate('Maungakiekie')
    the_election.add_electorate('Mt Albert')
    the_election.add_electorate('Mt Roskill')
    the_election.add_electorate('Napier')
    the_election.add_electorate('Nelson')
    the_election.add_electorate('New Lynn')
    the_election.add_electorate('New Plymouth')
    the_election.add_electorate('North Shore')
    the_election.add_electorate('Northcote')
    the_election.add_electorate('Northland')
    the_election.add_electorate('Ōhāriu')
    the_election.add_electorate('Ōtaki')
    the_election.add_electorate('Pakuranga')
    the_election.add_electorate('Palmerston')
    the_election.add_electorate('Panmure-Ōtāhuhu')
    the_election.add_electorate('Papakura')
    the_election.add_electorate('Port Waikato')
    the_election.add_electorate('Rangitata')
    the_election.add_electorate('Rangitīkei')
    the_election.add_electorate('Remutaka')
    the_election.add_electorate('Rongotai')
    the_election.add_electorate('Rotorua')
    the_election.add_electorate('Selwyn')
    the_election.add_electorate('Southland')
    the_election.add_electorate('Taieri')
    the_election.add_electorate('Takanini')
    the_election.add_electorate('Tāmaki')
    the_election.add_electorate('Taranaki-King Country')
    the_election.add_electorate('Taupō')
    the_election.add_electorate('Tauranga')
    the_election.add_electorate('Te Atatū')
    the_election.add_electorate('Tukituki')
    the_election.add_electorate('Upper Harbour')
    the_election.add_electorate('Waikato')
    the_election.add_electorate('Waimakariri')
    the_election.add_electorate('Wairarapa')
    the_election.add_electorate('Waitaki')
    the_election.add_electorate('Wellington Central')
    the_election.add_electorate('West Coast-Tasman')
    the_election.add_electorate('Whanganui')
    the_election.add_electorate('Whangaparāoa')
    the_election.add_electorate('Whangārei')
    the_election.add_electorate('Wigram')
    the_election.add_electorate('Hauraki-Waikato')
    the_election.add_electorate('Ikaroa-Rāwhiti')
    the_election.add_electorate('Tāmaki Makaurau')
    the_election.add_electorate('Te Tai Hauāuru')
    the_election.add_electorate('Te Tai Tokerau')
    the_election.add_electorate('Te Tai Tonga')
    the_election.add_electorate('Waiariki')

    #
    # the_election.set_winning_party('Auckland Central', 'Green Party')
    # the_election.set_winning_party('Banks Peninsula', 'Labour Party')
    # the_election.set_winning_party('Bay of Plenty', 'National Party')
    # the_election.set_winning_party('Botany', 'National Party')
    # the_election.set_winning_party('Christchurch Central', 'Labour Party')
    # the_election.set_winning_party('Christchurch East', 'Labour Party')
    # the_election.set_winning_party('Coromandel', 'National Party')
    # the_election.set_winning_party('Dunedin', 'Labour Party')
    # the_election.set_winning_party('East Coast', 'Labour Party')
    # the_election.set_winning_party('East Coast Bays', 'National Party')
    # the_election.set_winning_party('Epsom', 'ACT New Zealand')
    # the_election.set_winning_party('Hamilton East', 'Labour Party')
    # the_election.set_winning_party('Hamilton West', 'Labour Party')
    # the_election.set_winning_party('Hutt South', 'Labour Party')
    # the_election.set_winning_party('Ilam', 'Labour Party')
    # the_election.set_winning_party('Invercargill', 'National Party')
    # the_election.set_winning_party('Kaikōura', 'National Party')
    # the_election.set_winning_party('Kaipara ki Mahurangi', 'National Party')
    # the_election.set_winning_party('Kelston', 'Labour Party')
    # the_election.set_winning_party('Mana', 'Labour Party')
    # the_election.set_winning_party('Māngere', 'Labour Party')
    # the_election.set_winning_party('Manurewa', 'Labour Party')
    # the_election.set_winning_party('Maungakiekie', 'National Party')
    # the_election.set_winning_party('Mt Albert', 'Labour Party')
    # the_election.set_winning_party('Mt Roskill', 'Labour Party')
    # the_election.set_winning_party('Napier', 'Labour Party')
    # the_election.set_winning_party('Nelson', 'Labour Party')
    # the_election.set_winning_party('New Lynn', 'Labour Party')
    # the_election.set_winning_party('New Plymouth', 'Labour Party')
    # the_election.set_winning_party('North Shore', 'National Party')
    # the_election.set_winning_party('Northcote', 'Labour Party')
    # the_election.set_winning_party('Northland', 'National Party')
    # the_election.set_winning_party('Ōhāriu', 'Labour Party')
    # the_election.set_winning_party('Ōtaki', 'Labour Party')
    # the_election.set_winning_party('Pakuranga', 'National Party')
    # the_election.set_winning_party('Palmerston', 'Labour Party')
    # the_election.set_winning_party('Panmure-Ōtāhuhu', 'Labour Party')
    # the_election.set_winning_party('Papakura', 'National Party')
    # the_election.set_winning_party('Port Waikato', 'National Party')
    # the_election.set_winning_party('Rangitata', 'Labour Party')
    # the_election.set_winning_party('Rangitīkei', 'National Party')
    # the_election.set_winning_party('Remutaka', 'Labour Party')
    # the_election.set_winning_party('Rongotai', 'Labour Party')
    # the_election.set_winning_party('Rotorua', 'National Party')
    # the_election.set_winning_party('Selwyn', 'National Party')
    # the_election.set_winning_party('Southland', 'National Party')
    # the_election.set_winning_party('Taieri', 'Labour Party')
    # the_election.set_winning_party('Takanini', 'Labour Party')
    # the_election.set_winning_party('Tāmaki', 'National Party')
    # the_election.set_winning_party('Taranaki-King Country', 'National Party')
    # the_election.set_winning_party('Taupō', 'National Party')
    # the_election.set_winning_party('Tauranga', 'National Party')
    # the_election.set_winning_party('Te Atatū', 'Labour Party')
    # the_election.set_winning_party('Tukituki', 'Labour Party')
    # the_election.set_winning_party('Upper Harbour', 'Labour Party')
    # the_election.set_winning_party('Waikato', 'National Party')
    # the_election.set_winning_party('Waimakariri', 'National Party')
    # the_election.set_winning_party('Wairarapa', 'Labour Party')
    # the_election.set_winning_party('Waitaki', 'National Party')
    # the_election.set_winning_party('Wellington Central', 'Labour Party')
    # the_election.set_winning_party('West Coast-Tasman', 'Labour Party')
    # the_election.set_winning_party('Whanganui', 'Labour Party')
    # the_election.set_winning_party('Whangaparāoa', 'National Party')
    # the_election.set_winning_party('Whangārei', 'National Party')
    # the_election.set_winning_party('Wigram', 'Labour Party')
    # the_election.set_winning_party('Hauraki-Waikato', 'Labour Party')
    # the_election.set_winning_party('Ikaroa-Rāwhiti', 'Labour Party')
    # the_election.set_winning_party('Tāmaki Makaurau', 'Labour Party')
    # the_election.set_winning_party('Te Tai Hauāuru', 'Labour Party')
    # the_election.set_winning_party('Te Tai Tokerau', 'Labour Party')
    # the_election.set_winning_party('Te Tai Tonga', 'Labour Party')
    # the_election.set_winning_party('Waiariki', 'Māori Party')
    #
    # the_election.set_vote_percent('ACT New Zealand', 8.0)
    # the_election.set_vote_percent('Advance NZ', 0.9)
    # the_election.set_vote_percent('Aotearoa Legalise Cannabis Party', 0.3)
    # the_election.set_vote_percent('Green Party', 7.6)
    # the_election.set_vote_percent('HeartlandNZ', 0.0)
    # the_election.set_vote_percent('Labour Party', 49.1)
    # the_election.set_vote_percent('Māori Party', 1.0)
    # the_election.set_vote_percent('National Party', 26.8)
    # the_election.set_vote_percent('New Conservative', 1.5)
    # the_election.set_vote_percent('New Zealand First Party', 2.7)
    # the_election.set_vote_percent('NZ Outdoors Party', 0.1)
    # the_election.set_vote_percent('ONE Party', 0.3)
    # the_election.set_vote_percent('Social Credit', 0.1)
    # the_election.set_vote_percent('Sustainable New Zealand Party', 0.1)
    # the_election.set_vote_percent('TEA Party', 0.1)
    # the_election.set_vote_percent('The Opportunities Party (TOP)', 1.4)
    # the_election.set_vote_percent('Vision New Zealand', 0.1)


    return the_election

if __name__ == '__main__':
    election = setup()
    print(election)
